### ISSUE TITLE
FW Lite beta

### ISSUE THREAD

**Issue by hahn-kev** [sillsdev/languageforge-lexbox#1241]
This will be used to track what needs to be done to release a beta to our users

- [ ] auto update
- [ ] ms store release
- [ ] publish to sil software
- [ ] figure out project linking and picking/upload model
- [ ] figure out CRDT vs fwdata explanation to user
- [ ] bugs???
