### ISSUE TITLE
ICU based sorting

### ISSUE THREAD

**Issue by hahn-kev** [sillsdev/languageforge-lexbox#1289]
Right now we're just using naive standard sorting. We would like to sort correctly similar to FieldWorks. This issue does not track new sorting options, but does include custom sorting via the writing system config that fieldworks supports.

Todo
- [ ] add sort data to WritingSystem model in miniLcm
- [ ] change sorting to utilize ICU based on the WsId being sorted by
- [ ] sorting tests, there's probably some in Lcm or somewhere else to start from.
