### ISSUE TITLE
Support custom fields

### ISSUE THREAD

**Issue by hahn-kev** [sillsdev/languageforge-lexbox#1302]
Custom fields are quite complicated, however they're very important to a lot of users, so we need to support them eventually.

[FW Help](https://downloads.languagetechnology.org/fieldworks/Documentation/en/index.htm#t=User_Interface%2FMenus%2FTools%2FCustom_Fields%2FCustom_Fields_overview.htm)

Model:
- [ ] develop a model for custom field definitions
- [ ] develop a data model for custom field data on Entry, Sense, Example sentence
- [ ] develop a generic model for custom lists

Api:
- [ ] develop api for interacting with custom fields, list fields, create new, delete etc
- [ ] develop api for listing all/custom lists and for interacting with them, CRUD

Ui:
- [ ] UI in FW Lite for showing custom fields (not editing field definitions) and editing data

notes:

- FW Help suggests a limit of 100 custom fields, I suggest we enforce that
