### ISSUE TITLE
Organizations

### ISSUE THREAD

**Issue by hahn-kev** [sillsdev/languageforge-lexbox#576]
We want to organize projects and users into organizations. This will allow us to have org admins and narrow the scope of their permissions. It will also allow us to determine data ownership. It also better enables guest accounts

- [x] #779
- [x] #881
- [x] #776
- [x] #762
- [x] #780
- [x] #778
- [x] #788
- [x] Add orgs to JWT (and make sure we refresh the JWT appropriately e.g. by using the `RefreshJwtAttribute` and `RefreshJwtProjectMembershipMiddleware` as we've done for project mutation)
- [x] Allow users to be admins of an org
- [ ] make guest users owned by an org instead of an admin (still need to preserve who they were created by for GDPR compliance tracking)
- [x] #930
- [ ] create help docs for adding users to orgs, current links show the project member process
- [x] #879
- [x] #934
